// lib/tnCounties.ts
// Simple county list for the Buy Box MVP.
// You can expand this later (or replace with a DB-driven list).

export const MIDDLE_TN_COUNTIES = [
  "Davidson",
  "Williamson",
  "Rutherford",
  "Sumner",
  "Wilson",
  "Maury",
  "Robertson",
  "Montgomery",
  "Cheatham",
  "Dickson",
  "Bedford",
  "Cannon",
  "Coffee",
  "Hickman",
  "Humphreys",
  "Stewart",
  "Trousdale",
  "Wayne",
  "Lewis",
  "Perry",
  "Giles",
  "Marshall",
  "Lawrence",
  "Lincoln",
  "Franklin",
  "Warren",
  "Putnam",
  "White",
  "Overton",
  "Macon",
  "Smith",
  "DeKalb",
  "Jackson",
  "Fentress",
  "Cumberland",
  "Clay",
  "Pickett",
];
